language: python
python:
  - "3.6" 
  
install:
  - pip install -r requirements.txt  
 
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE sendit;" -U postgres
  

script:
  - pytest --cov
  - coverage report

after_success:
  - coveralls 
